language: objective-c
os: osx
osx_image: xcode7
before_install:
- export LANG=en_US.UTF-8
- brew update
- npm install -g npm@2.14.7
- npm install -g grunt-cli cordova ionic
before_script:
- ls
script:
- npm install
- ionic platform add ios
- ionic plugin add ionic-plugin-keyboard
- ionic build ios --device --release
after_script:
- ls -a platforms/ios